# Generated by Django 5.2 on 2025-06-02 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restock_level',
            field=models.IntegerField(default=0, help_text='Minimum stock quantity to trigger a reorder.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
