# Generated by Django 5.2 on 2025-06-06 03:35

from django.db import migrations, models
import django.utils.timezone # Import timezone

def populate_transaction_numbers(apps, schema_editor):
    Stock = apps.get_model('core', 'Stock')
    # Get all stock objects, order by pk to ensure consistent numbering
    stock_objects = Stock.objects.order_by('pk')
    for i, stock in enumerate(stock_objects, 1):
        stock.transaction_number = i
        stock.save(update_fields=['transaction_number'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['transaction_number']},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='stock',
            name='transaction_number',
            field=models.PositiveIntegerField(db_index=True, null=True), # Made nullable and removed unique=True
        ),
        # Run the data migration to populate transaction_number after adding the field
        migrations.RunPython(populate_transaction_numbers, migrations.RunPython.noop),
    ]
