# Generated by Django 5.2 on 2025-06-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_stock_options_remove_stock_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['transaction_number'], 'verbose_name_plural': 'Stock Transactions'},
        ),
        migrations.AddField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date of the batch', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference number for the transaction (e.g., PO number, SO number)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='transaction_number',
            field=models.PositiveIntegerField(db_index=True, null=True, unique=True),
        ),
    ]
