# Generated by Django 5.2 on 2025-06-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_stock_options_stock_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['reference_number'], 'verbose_name_plural': 'Stock Transactions'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='transaction_number',
        ),
        migrations.AlterField(
            model_name='stock',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
