# Generated by Django 5.0.2 on 2025-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_stock_options_remove_stock_transaction_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='client_name',
            field=models.CharField(blank=True, help_text='Name of the client for this transaction.', max_length=200, null=True),
        ),
    ]
