# Generated by Django 5.0.2 on 2025-06-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sale_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Optional reference for the transaction, e.g., receipt number.', max_length=50, null=True),
        ),
    ]
